export const GET_IMAGES = "GET_IMAGES";
export const LOAD_MORE = "LOAD_MORE";
export const IMAGES_LOADING = "IMAGES_LOADING";
export const IMAGES_LOADING_MORE = "IMAGES_LOADING_MORE";
export const UPDATE_QUERY = "UPDATE_QUERY";
export const INCREMENT_PAGE = "INCREMENT_PAGE";